### ISSUE TITLE
リソース・DB設計をする

### ISSUE THREAD

**Issue by omochiumaiumai** [omochiumaiumai/fjord-walk#8]
# リソース・DB設計(決定)
### ログイン
| Method | Path | Description |
| ---- | ---- | ---- |
| GET | / | ログインページ(トップページ)を表示。 |
| GET | /auth/:provider(discord)/callback | OAuth 2.0(omniauth-discord)ログイン処理/ユーザー作成の処理 |
| GET | /log_out | ログアウト |
### ダッシュボード
| Method | Path | Description |
| ---- | ---- | ---- |
| GET | /dashbord | ダッシュボード(出席カレンダー、直近の参加予定のイベントなど)を表示 |
| POST | /events/:event_id/attendance | 直近のイベントへの出席登録 |
| DELETE | /events/:event_id/attendance/:user_id | 直近のイベントへの出席登録を取り消し |

### プロフィール(マイページ)
| Method | Path | Description |
| ---- | ---- | ---- |
| GET | /users/:user_id | ユーザー名、直近のイベント参加日、通算の参加日数を表示/自分のページのみ出席カレンダーの履歴を表示(Swiper.jsでの実装) |
| GET | /users/:user_id/edit| ユーザー名(表示名・読み上げる名前)の編集フォームを表示|
| PUT | /users/:user_id | ユーザー情報を更新 | 

#### イベント
| Method | Path | Description |
| ---- | ---- | ---- |
| GET | /events | イベント一覧を表示 |
| GET | /events/:event_id | イベント詳細を表示 |
| POST | /events/:event_id/participants | イベントに参加 |
| DELETE | /events/:event_id/participants/:user_id | イベント参加取り消し |
| GET | /events/new | イベント新規作成フォームを表示| 
| POST | /events | イベントを新規作成 |
| GET | /events/:event_id/edit | イベント編集フォームを表示 | 
| PUT | /events/:event_id | イベント情報を編集 | 
| POST | /events/:event_id/request_deletion | イベント削除申請 |

#### トークテーマ
| Method | Path                                         | Description      |
|--------|----------------------------------------------|------------------|
| GET    | /events/:event_id/talk_theme                 | イベントごとのトークテーマを表示 |
| POST   | /events/:event_id/talk_theme                 | トークテーマを追加        |
| DELETE | /events/:event_id/talk_theme/:talk_theme_id  | トークテーマを削除        |

### サービスページ
| Method | Path | Description |
| ---- | ---- | ---- |
| GET | /description | サービスの詳細な説明を表示|

### ヘルプ(操作方法)ページ
| Method | Path | Description |
| ---- | ---- | ---- |
| GET | /how_to | 読み上げBotの操作説明を表示 |

## DB
<img width="967" alt="image" src="https://github.com/user-attachments/assets/74ece41c-43f1-4c33-a362-6cb4e6014f74">

---

<details><summary>初期案</summary>

### ログイン
| Method | Path | Description |
| ---- | ---- | ---- |
| GET | / | ログインページ(トップページ)を表示。 |
| GET | /auth/:provider(discord)/callback | OAuth 2.0(omniauth-discord)ログイン処理/ユーザー作成の処理 |
| GET | /log_out | ログアウト |
### ダッシュボード
| Method | Path | Description |
| ---- | ---- | ---- |
| GET | /dashbord | ダッシュボード(出席カレンダー、直近の参加予定のイベントなど)を表示 |
### プロフィール(マイページ)
| Method | Path | Description |
| ---- | ---- | ---- |
| GET | /users/:user_id | ユーザー名、直近のイベント参加日、通算の参加日数を表示/自分のページのみ出席カレンダーの履歴を表示(Swiper.jsでの実装) |
| GET | /users/:user_id/edit| ユーザー名(表示名・読み上げる名前)の編集フォームを表示|
| PUT | /users/:user_id | ユーザー情報を更新 | 

こちらはペーパープロトタイプからの変更点があります(ページ下部にて説明)

#### イベント
| Method | Path | Description |
| ---- | ---- | ---- |
| GET | /events | イベント一覧を表示 |
| GET | /events/:event_id | イベント詳細を表示 |
| POST | /events/:event_id/join | イベントに参加 |
| DELETE | /events/:event_id/leave | イベント参加取り消し |
| GET | /events/new | イベント新規作成フォームを表示| 
| POST | /events | イベントを新規作成 |
| GET | /events/:event_id/edit | イベント編集フォームを表示 | 
| PUT | /events/:event_id | イベント情報を編集 | 
| POST | /events/:event_id/request_deletion | イベント削除申請 |

#### トークテーマ
| Method | Path | Description |
| ---- | ---- | ---- |
| GET | /events/:event_id/talk_theme | イベントごとのトークテーマを表示 |
| POST | /events/:event_id/talk_theme | トークテーマを追加 |
| DELETE | /events/:event_id/talk_theme | トークテーマを削除 |

### サービスページ
| Method | Path | Description |
| ---- | ---- | ---- |
| GET | /description | サービスの詳細な説明を表示|

### ヘルプ(操作方法)ページ
| Method | Path | Description |
| ---- | ---- | ---- |
| GET | /how_to | 読み上げBotの操作説明を表示 |

## DB設計
![image](https://github.com/user-attachments/assets/21b675ba-c1f2-4717-8b44-d7e3025be3e7)
Eventsのstatusはイベントの状態管理に使用します(active / deleted)

## ペーパープロトタイプからの変更点について
マイページは編集の機能をつけない予定でしたが、ユーザー名を変更できるようにします。
![Image](https://github.com/user-attachments/assets/320ab5fd-97a0-45b6-a1c7-d5bdcea10df6)
技術検証の結果、Discordからユーザー名は取得できても表示名の取得は方法が見つからないため、マイページに編集フォームを設けてユーザー自身に表示名を登録してもらう方向で実装を進めています。

### 処理の流れ
以下のような実装を考えています。

1. イベントの作成
イベントを作成する際に使用するBot、ボイスチャンネルのidを選択
2. Botの起動
ボイスチャンネルに参加し、テキストチャンネル ` #fjord-walk `でBotを起動
3. イベントの特定
ボイスチャンネルへの参加時刻と使用するBotのIDをもとに、データベースから関連するイベントを特定
4. イベント情報の受け渡し
特定されたイベントから参加者とトークテーマの情報をBotに渡す
5. コマンドでの操作
Botにコマンドを送信して、指定されたトークテーマや参加者の情報を読み上げさせる

一つのBotは同じ時間に複数のボイスチャンネルに参加できないため、複数のBot（Bot1、Bot2）を用意し、イベント作成時に使用するBotを選択してもらう仕組みを考えています。
この際にバリデーションを設定して、同じ時間帯に複数のイベントで同じBotが選択されることを防ぐ実装方法で進めています。

</details>

**Comment by yuuu** [comment]
確認しました 👍 気になった点をコメントします。

### リソース

- `イベントに参加` のパスを `/events/:event_id/join` としていますが、DB設計には `EventParticipants` というテーブルが存在していますね。イベントに参加するということは「 `EventParticipants` を `create` する」ということではないでしょうか？
    - そう考えるとここのPathを見直した方がいわゆるRESTfulなものになるはずです
- 出欠に関するリソース定義がありませんが、漏れていないでしょうか？
    - `AttendanceRecords` をどのタイミングでcreate/destroyするのかが気になりました。
- [質問] Botはユーザーが新規登録するシチュエーションはなく、基本的にシステム側から選択肢が提供されるもの、という理解であっていますか？
    - Botの一覧や新規登録の画面が不要かどうかが気になりました

### DB

- `イベント削除申請テーブル` を作る必要はないでしょうか？
    - 今の設計だといつ・誰がイベント削除申請をしたか、という記録が残らないように見えます
    - ペーパープロトタイプにはないですがもしかすると「イベント削除申請一覧」のような画面も必要なのでは？と感じました
- トークテーマとユーザーのリレーションは不要でしょうか？
    - ペーパープロトタイプには `自分が追加したものに限り【削除】ボタンが表示され` という記載があったので必要に見えます
- `AttendanceRecords` という名前について、大抵のテーブルは `Records` を持つものなので、 `Records` は省略しましょう

### その他質問

- 「朝散歩」というものについて、自分の解像度が低いので、詳細を教えていただきたいです。
    - 複数の参加者がDiscordのトークチャンネルに入って、それぞれ自分のお家周辺を歩くきながらお話するイベント、という理解であってますか？
- 今回、管理者専用のページは作成しない認識であっていますか？

**Comment by omochiumaiumai** [comment]
@yuuu
レビューありがとうございます！
前回から変更点があるためお知らせします。
### Botの仕様変更について
> 一つのBotは同じ時間に複数のボイスチャンネルに参加できないため、複数のBot（Bot1、Bot2）を用意し、イベント作成時に使用するBotを選択してもらう仕組みを考えています。
> この際にバリデーションを設定して、同じ時間帯に複数のイベントで同じBotが選択されることを防ぐ実装方法で進めています。

改めて検証した結果、アプリケーションの仕様上2つのBotの運用は難しいと判断したため、以上の案はボツとさせていただきます。
同じ時間に開催されるイベントの作成をバリデーションで防ぎ、attendanceが存在するユーザーのnameを取得し、botに渡す仕様に変更します。

このため、Botの管理に関するテーブルは不要考えER図から削除しております。

## リソース設計(改訂)
### ログイン
| Method | Path | Description |
| ---- | ---- | ---- |
| GET | / | ログインページ(トップページ)を表示。 |
| GET | /auth/:provider(discord)/callback | OAuth 2.0(omniauth-discord)ログイン処理/ユーザー作成の処理 |
| GET | /log_out | ログアウト |
### ダッシュボード
| Method | Path | Description |
| ---- | ---- | ---- |
| GET | /dashbord | ダッシュボード(出席カレンダー、直近の参加予定のイベントなど)を表示 |
| POST | /events/:event_id/attendance | 直近のイベントへの出席登録 |
| DELETE | /events/:event_id/attendance/:user_id | 直近のイベントへの出席登録を取り消し |


### プロフィール(マイページ)
| Method | Path | Description |
| ---- | ---- | ---- |
| GET | /users/:user_id | ユーザー名、直近のイベント参加日、通算の参加日数を表示/自分のページのみ出席カレンダーの履歴を表示(Swiper.jsでの実装) |
| GET | /users/:user_id/edit| ユーザー名(表示名・読み上げる名前)の編集フォームを表示|
| PUT | /users/:user_id | ユーザー情報を更新 | 

### イベントページ
#### イベント
| Method | Path | Description |
| ---- | ---- | ---- |
| GET | /events | イベント一覧を表示 |
| GET | /events/:event_id | イベント詳細を表示 |
| POST | /events/:event_id/participants | イベントに参加 |
| DELETE | /events/:event_id/participants/:user_id | イベント参加取り消し |
| GET | /events/new | イベント新規作成フォームを表示| 
| POST | /events | イベントを新規作成 |
| GET | /events/:event_id/edit | イベント編集フォームを表示 | 
| PUT | /events/:event_id | イベント情報を編集 | 
| POST | /events/:event_id/request_deletion | イベント削除申請 |

#### トークテーマ
| Method | Path                                         | Description      |
|--------|----------------------------------------------|------------------|
| GET    | /events/:event_id/talk_theme                 | イベントごとのトークテーマを表示 |
| POST   | /events/:event_id/talk_theme                 | トークテーマを追加        |
| DELETE | /events/:event_id/talk_theme/:talk_theme_id  | トークテーマを削除        |

### サービスページ
| Method | Path | Description |
| ---- | ---- | ---- |
| GET | /description | サービスの詳細な説明を表示|

### ヘルプ(操作方法)ページ
| Method | Path | Description |
| ---- | ---- | ---- |
| GET | /how_to | 読み上げBotの操作説明を表示 |

---

> イベントに参加 のパスを /events/:event_id/join としていますが、DB設計には EventParticipants というテーブルが存在していますね。イベントに参加するということは「 EventParticipants を create する」ということではないでしょうか？

ご指摘のとおりです。修正しました。

---

> 出欠に関するリソース定義がありませんが、漏れていないでしょうか？

ご指摘ありがとうございます。
 設計漏れのためリソースを追加しました。

> AttendanceRecords をどのタイミングでcreate/destroyするのかが気になりました。

ダッシュボードに参加登録をしている直近のイベントの出席/出席取り消しができるボタンが出現し、イベント開始前にこのボタンを押して出席(Attendance)のcreate/destroyをします。

---

> [質問] Botはユーザーが新規登録するシチュエーションはなく、基本的にシステム側から選択肢が提供されるもの、という理解であっていますか？

> Botの一覧や新規登録の画面が不要かどうかが気になりました

はい。Botはイベントに紐づいた参加者の名前とトークテーマをランダムに音声で案内するだけのため、ユーザーが新規登録する場面はありません。

## DB設計

![Image](https://github.com/user-attachments/assets/522c9f01-7911-489b-9807-2324f70e77b4)

---
> イベント削除申請テーブル を作る必要はないでしょうか？
> 今の設計だといつ・誰がイベント削除申請をしたか、という記録が残らないように見えます
> ペーパープロトタイプにはないですがもしかすると「イベント削除申請一覧」のような画面も必要なのでは？と感じました

こちらについて共有できておらず失礼いたしました。
サービス考案者のmachidaさんとのヒアリングで、
- イベント削除申請ができるのはイベント作成者のみ
- イベント作成者から削除申請を受け、イベントを手動で論理削除(アーカイブ化)する

以上のように決定したため、イベント削除申請テーブルとイベント削除申請一覧は不要であると考えております。

---

> トークテーマとユーザーのリレーションは不要でしょうか？
>  ペーパープロトタイプには 自分が追加したものに限り【削除】ボタンが表示され という記載があったので必要に見えます

ご指摘ありがとうございます。トークテーマとユーザーのリレーションは必要なため、ER図を更新しました。

### その他質問
> 「朝散歩」というものについて、自分の解像度が低いので、詳細を教えていただきたいです。
> 複数の参加者がDiscordのトークチャンネルに入って、それぞれ自分のお家周辺を歩くきながらお話するイベント、という理解であってますか？

はい。イベントに参加登録+出席登録したユーザーが、ボイスチャンネルに参加して散歩しながらお話するイベントになります。
この際にbotもボイスチャンネルに参加し、テキストチャンネルにてコマンドで発言するユーザー、トークテーマを決定してもらい、話す人や話題が偏らないようにするのがサービスの目的です。

> 今回、管理者専用のページは作成しない認識であっていますか？

今回は管理者専用のページは作成しません。

---
再度レビューをよろしくお願いいたします🙇‍♂

**Comment by yuuu** [comment]
@omochiumaiumai 
修正ありがとうございます 👍 全体的に良くなっていますね ✨ 
あと1点だけ確認させてください。

> イベント作成者から削除申請を受け、イベントを手動で論理削除(アーカイブ化)する

削除申請があったとき、イベント作成者はどのように通知を受ける想定でしょうか？

**Comment by omochiumaiumai** [comment]
@yuuu 
お疲れ様です！
レビューありがとうございます。
> 削除申請があったとき、イベント作成者はどのように通知を受ける想定でしょうか？

Method | Path
-- | --
POST | /events/:event_id/request_deletion

こちらについては削除申請ボタンを押した後にフラッシュで`削除申請を受け付けました。`のようなメッセージを出す予定です。

**Comment by yuuu** [comment]
@omochiumaiumai 
失礼しました。自分の文章が誤っていますね。
「イベントを手動で論理削除する人」が「そのイベントへの削除申請」にどうやって気づく想定をしているのか、確認したかったです 🙏

**Comment by omochiumaiumai** [comment]
@yuuu 
お疲れ様です。レビューありがとうございます🙇‍♂
> 「イベントを手動で論理削除する人」が「そのイベントへの削除申請」にどうやって気づく想定をしているのか、確認したかったです 🙏

ER図のイベントテーブルに`deletion_requested`のカラムが抜けていたためこちらを修正しました。
<img width="967" alt="image" src="https://github.com/user-attachments/assets/608f4983-8b10-4079-a7f9-fb0dd0e16681">

POSTが行われたときにこの`deletion_requested`の値をtrueに書き換え、ActionMailerで管理者宛に削除リクエストのメールが届くような実装を考えています。
```ruby
def deletion_request
    @event = Event.find(params[:event_id])
    @event.update(deletion_requested: true)
    EventMailer.deletion_request(@event).deliver_now
 end
```

**Comment by yuuu** [comment]
@omochiumaiumai 
なるほど、カラムに記録を残しつつメールで通知予定ということですね。理解できました 👍

**Comment by omochiumaiumai** [comment]
レビューが完了したためCloseします。
